# Global config for MedMNIST-EdgeAI

project:
  name: MedMNIST-EdgeAI
  seed: 42

data:
  dir: data                        # Root data directory
  dataset: pathmnist              # Options: pathmnist, chestmnist, dermamnist, etc.
  image_size: 28                  # All MedMNIST images are 28x28
  batch_size: 64
  num_workers: 0

model:
  teacher_arch: resnet50          # Teacher model architecture
  student_arch: mobilenetv3       # Future student model (for distillation)
  pretrained: true
  dynamic_fc: true                # Enable automatic fc adaptation to class count

train:
  epochs: 20
  lr: 0.001
  weight_decay: 0.0001
  optimizer: adam                 # Options: adam, sgd

log:
  interval: 10
  save_dir: models/               # Checkpoints, saved weights
  log_dir: logs/                  # (Optional) TensorBoard/W&B
